import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Analytics } from "@vercel/analytics/react"
import { getServerSession } from 'next-auth'
import SessionProvider from "./components/SessionProvider"


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Superpost',
  description: 'Generated by create next app',
}

export default async function  RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession()
  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={`${inter.className} relative`}>
        {/* <Navbar></Navbar> */}
          {children}
          <Analytics/>
        {/* <Footer></Footer> */}
        </body>
      </SessionProvider>
      
    </html>
  )
}
